

SELECT * FROM parque_vehicular_datos WHERE ISNUMERIC(VALOR_DEL_VEHICULO)=1
SELECT COUNT(*),CILINDRADA FROM parque_vehicular_datos GROUP BY CILINDRADA

UPDATE parque_vehicular_datos SET CAPACIDAD = '0' WHERE CAPACIDAD = ''


--DROP TABLE DB_parque_vehicular_datos
CREATE TABLE DB_parque_vehicular_datos (Id INT IDENTITY(1,1),
										TIPO_PLACA VARCHAR(50),
										ANIO_DE_FABRICACION INT,
										CILINDRADA VARCHAR(10),
										CANTIDAD_DE_CILINDROS VARCHAR(10),
										CANTIDAD_DE_PUERTAS VARCHAR(10),
										VALOR_DEL_VEHICULO NUMERIC(12,2),
										COLORES VARCHAR(100),
										FECHA_DE_IMPORTACION VARCHAR(25),
										IMP_VALOR_DEL_VEHICULO NUMERIC(12,2),
										FECHA_DE_INGRESO DATE,
										ANIO_INGRESO INT,
										MES_INGRESO INT,
										CLASE VARCHAR (50),
										PERTENENCIA VARCHAR(50),
										MARCA VARCHAR(50),
										MODELO VARCHAR(50),
										CAPACIDAD NUMERIC(12,2),
										COMBUSTIBLE VARCHAR(25),
										ADUANA VARCHAR(50),
										CONDICION_INGRESO VARCHAR(50),
										PROPIETARIO_DEPARTAMENTO VARCHAR(50),
										PROPIETARIO_MUNICIPIO VARCHAR(50),
										ESTADO VARCHAR(20))

INSERT INTO DB_parque_vehicular_datos (TIPO_PLACA,ANIO_DE_FABRICACION,CILINDRADA,CANTIDAD_DE_CILINDROS,CANTIDAD_DE_PUERTAS,VALOR_DEL_VEHICULO,COLORES,
                                       FECHA_DE_IMPORTACION,IMP_VALOR_DEL_VEHICULO,FECHA_DE_INGRESO,ANIO_INGRESO,MES_INGRESO,CLASE,PERTENENCIA,MARCA,
									   MODELO,CAPACIDAD,COMBUSTIBLE,ADUANA,CONDICION_INGRESO,PROPIETARIO_DEPARTAMENTO,PROPIETARIO_MUNICIPIO,ESTADO)
SELECT TIPO_PLACA,ANIO_DE_FABRICACION,CILINDRADA,CANTIDAD_DE_CILINDROS,CANTIDAD_DE_PUERTAS,VALOR_DEL_VEHICULO,COLORES,
                                       FECHA_DE_IMPORTACION,IMP_VALOR_DEL_VEHICULO,FECHA_DE_INGRESO,ANIO_INGRESO,MES_INGRESO,CLASE,PERTENENCIA,MARCA,
									   MODELO,CAPACIDAD,COMBUSTIBLE,ADUANA,CONDICION_INGRESO,PROPIETARIO_DEPARTAMENTO,PROPIETARIO_MUNICIPIO,ESTADO 
FROM parque_vehicular_datos 


ISNUMERIC(CANTIDAD_DE_PUERTAS)=1
ISNUMERIC(TIPO_PLACA)=1

ISNUMERIC(ANIO_DE_FABRICACION)=1
ISNUMERIC(IMP_VALOR_DEL_VEHICULO)=1